---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-system
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: examples
spec:
  owner: guests
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-component
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: example-website
spec:
  type: website
  lifecycle: experimental
  owner: guests
  system: examples
  providesApis: [example-grpc-api]
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-api
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: example-grpc-api
spec:
  type: grpc
  lifecycle: experimental
  owner: guests
  system: examples
  definition: |
    syntax = "proto3";

    service Exampler {
      rpc Example (ExampleMessage) returns (ExampleMessage) {};
    }

    message ExampleMessage {
      string example = 1;
    };
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: genesys
  title: Genesys
  description: Genesys is an application for customer support.
spec:
  type: application
  lifecycle: production
  owner: atendimento
  consumesApis:
    - atendimento-inovacao
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: robbu
  title: Robbu
  description: Robbu é parceiro que realiza fluxos financeiros via Whatsapp, consumindo a API de atendimento inovação.
spec:
  type: application
  lifecycle: production
  owner: atendimento
  consumesApis:
    - atendimento-inovacao
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: mundiale
  title: Mundiale
  description: Mundiale é um parceiro que gera orçamentos e é um consumidor da API de atendimento inovação.
spec:
  type: application
  lifecycle: production
  owner: atendimento
  consumesApis:
    - atendimento-inovacao
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: site-brisanet
  title: Site Brisanet
  description: O site da Brisanet é um consumidor da API de atendimento inovação para geração de orçamentos.
spec:
  type: website
  lifecycle: production
  owner: atendimento
  consumesApis:
    - atendimento-inovacao
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: vendas-app
  title: Vendas App
  description: App de vendas interno para geração de orçamentos.
spec:
  type: application
  lifecycle: planned
  owner: atendimento
  consumesApis:
    - atendimento-inovacao

# Atendimento
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: atendimento
  title: Sistema de Atendimento
  description: Agrupamento de serviços relacionados ao atendimento ao cliente
spec:
  owner: equipe-inovacao


# IRA
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: atendimento-inovacao
  title: Atendimento Inovação
  description: Microserviço em Go que expõe APIs para atendimento ao cliente
  tags:
    - go
    - microservice
  annotations:
    backstage.io/source-location: url:http://github.com/Brisanet/atendimento-inovacao/
    backstage.io/techdocs-ref: url:https://github.com/Brisanet/atendimento-inovacao/blob/master/server/docs/swagger.yaml
spec:
  type: service
  lifecycle: production
  owner: equipe-inovacao
  system: atendimento
  providesApis:
    - atendimento-inovacao
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: atendimento-inovacao
  title: atendimento-inovacao-api
  description: API para atendimento ao cliente
spec:
  type: openapi
  lifecycle: production
  owner: equipe-inovacao
  system: atendimento
  definition: |
    openapi: 3.0.0
    info:
      title: Atendimento Inovação
      version: 1.0.0
    paths:
      /v1/clients:
        get:
          summary: Lista clientes
      /v1/clients/register:
        post:
          summary: Registra novo cliente

# ION
---

apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ion-design-system
  title: Ion Design System
  description: Biblioteca Angular com os componentes reutilizáveis do design system institucional.
  tags:
    - angular
    - design-system
    - library
    - frontend
  annotations:
    github.com/project-slug: brisanet/ion
  links:
    - url: https://www.figma.com/design/HwQjnUI5ASA7YYmnahLVQS/Design-System?node-id=0-1&p=f&t=A4kMPxyQQFKYie38-0
      title: Figma - Design Tokens e Componentes
      icon: figma
    - url: https://main--62eab350a45bdb0a5818520e.chromatic.com/
      title: Storybook - Componentes
      icon: storybook
    - url: https://github.com/Brisanet/ion
      title: Repositório GitHub
      icon: github
    - url: https://github.com/Brisanet/ion/actions/workflows/release.yml
      title: Pipeline CI/CD
      icon: github
spec:
  type: library
  lifecycle: production
  owner: equipe-ion
  system: plataforma-frontend
---

# Backstage application configuration
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage
  description: backstage.io
  annotations:
    github.com/project-slug: 'backstage/backstage'
spec:
  type: website
  lifecycle: production
  owner: user:guest
---
